SERVER_NAME=chatserver_ynp_1.0
FIFO_DIR=~/Server/fifo
REG_FIFO=ynp_reg_fifo
LOGIN_FIFO=ynp_login_fifo
MSG_FIFO=ynp_msg_fifo
LOGOUT_FIFO=ynp_logout_fifo
LOG_DIR=~/log/chat-logs/server
SERVER_LOG=server.log
THREAD_LOG=threads.log
POOLSIZE=100
